### PR TITLE
Create Hebb_rule.m

### PR DESCRIPTION
**Pull request by rsh7**
I have added a Matlab implementation of Hebb rule, an algorithm in Neural Networks.

### CODE REVIEW

**Review by ShubhamSetia — CHANGES_REQUESTED** [review]
Code is fine,create a folder by name of Neural_Networks and add this file to that folder.

**Comment by rsh7** [comment]
I have added a Neural_Networks folder with a Hebb_rule.m file

**Review by ShubhamSetia — APPROVED** [review]
Thanks for your contribution, If possible add comments related to what a particular variable means and what you are trying to do so that beginners can also understand.

**Comment by rsh7** [comment]
Yeah sure!
I will add some comments to the code soon. :-)

**Comment by divyanshu-rawat** [comment]
@RashiSah  thanks for your PR 👍

**Pull request merged**
