### PR TITLE
Introductory code for Random Forests.

### PR DESCRIPTION
**Pull request by vibhor98**

### CODE REVIEW

**Review by divyanshu-rawat — COMMENTED** [review]
let's wait for other reviewers.

**Comment by ShubhamSetia** [comment]
create a separate sub-repository by the name Random Forest and push the code by name intro_to_random_forest.py or something like that and also write a comment in 9th line about what does n_estimators means (no of trees) as for beginners might not know what it means and i was thinking that we should create a separate branch for each algorithm instead of directly pushing on master. I made the mistake of pushing code directly on master but from now it would be better if we create separate branch for each algorithm. I will update this  in contributing.md

**Comment by ShubhamSetia** [comment]
and one more thing in training data add few more cases. Now you have just taken 2 examples only in training data set take atleast  5

**Comment by divyanshu-rawat** [comment]
@shubham Setia it would be great if you review or suggest changes from here https://github.com/Cybros/Lectures-On-Machine-Learning/pull/3/files.
You will find a green button on the right-hand side.

That's why you can still see the yellow dot in the below-mentioned pic it shows that you haven't reviewed the PR till so far.

sethia

**Comment by vibhor98** [comment]
Ok, I'll do as you stated.

**Comment by vibhor98** [comment]
Please review the PR. I've fulfilled all the requirements.

**Review by divyanshu-rawat — COMMENTED** [review]
wait for Shubham to approve:+1:

**Review by ShubhamSetia — APPROVED** [review]
Looks fine

**Comment by divyanshu-rawat** [comment]
@ShubhamSetia  if it is fine then I am merging it.

**Review by divyanshu-rawat — APPROVED** [review]
thanks for the PR   :+1:

**Pull request merged**
